### PR TITLE
Update to ttfautohint 1.8.4, freetype 2.11.1 and harfbuzz 3.3.2

### LINKED ISSUE #10: need to update embedded ttfautohint to latest 1.8.4
currently we ship with 1.8.3, but there's a more recent version: https://sourceforge.net/projects/freetype/files/ttfautohint/1.8.4/

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes #10

### CODE REVIEW

**Comment by anthrotype** [comment]
It turns out in 2022 one can't still have a folder named "aux" on Windows.

Try do `git clone https://repo.or.cz/ttfautohint.git` from a Windows console, and you'll get 

```
error: invalid path 'aux/qtlocation-2.patch'
```

https://ci.appveyor.com/project/fonttools/ttfautohint-py/build/job/aebijbpq03by6nom#L25

Because... => https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by anthrotype** [comment]
argh.. I have no idea why the libttfautohint.dll isn't loading correctly on Windows.. :(
It is building and installing seemingly without errors, but then the test fails to import it.
I'd have to try replicate this on a local windows machine to debug this.

**Comment by anthrotype** [comment]
I tried to build it on a local windows machine and the DLL loads just fine. I have no idea what's going on on the windows CI

**Comment by anthrotype** [comment]
aargh.. Even after switching from appveyor to github ci I keep getting the same issue, the libttfautohint.dll is built successfully but fails to load with the following error:

```
FileNotFoundError: Could not find module 'C:\Users\runneradmin\AppData\Local\Temp\tmp7z9xtkpb\lib\site-packages\ttfautohint\libttfautohint.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

https://github.com/fonttools/ttfautohint-py/runs/5094167498?check_suite_focus=true#step:7:2239

**Comment by anthrotype** [comment]
it turns out the reason is recent freetype automatically attempts to link with pthread library whenever that's available (needed for its enhanced FT_DEBUG_LOGGING feature, which we actually don't need); but then we don't include static pthread in the libttfautohint.dll so loading the latter fails..

(thanks to @madig for help finding this out and for the screenshot)

image

I need to figure out a way to tell freetype to _not_ link with pthread even if it _can_ find the library...

**Comment by anthrotype** [comment]
(adding pthread from mingw-w64 means we'd have to pull in the whole mingw runtime and I don't want to do that)

**Comment by anthrotype** [comment]
I'm almost ready to merge this (just waiting on the bots to complete). It took me a long time to make this work.. I had to resort to patching freetype and harfbuzz's configure.ac scripts to prevent the `AX_PTHREAD` macro to be run on Windows MinGW-w64 environment, as that was pulling in the unwanted libpthreads.dll dependency. Remote debugging is not fun, but I am happy that this now works again. For the time being, that is.. 😅

**Comment by lemzwerg** [comment]
@anthrotype, is there something to be added for FreeType?  I did a ping in https://gitlab.freedesktop.org/freetype/freetype/-/issues/1131 (which I've just closed due to inactivity), but you didn't respond...

**Comment by anthrotype** [comment]
@lemzwerg thanks for the ping, honestly I don't know, I haven't tried to rebuild ttfautohint from source in a while. I'll let you know when we do in case we find any issues

**Pull request merged**
